name: Audit JavaScript

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/audit-javascript.yml'
      - '**/yarn.lock'
      - '**/package.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/audit-javascript.yml'
      - '**/yarn.lock'
      - '**/package.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "yarn"
      
      - name: Install Dependencies
        run: |
          yarn set version latest
           yarn install --immutable

      - name: audit
        run: yarn audit
