name: Lint JavaScript

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/lint-javascript.yml'
      - 'frontend/**'
  pull_request:
    paths:
      - '.github/workflows/lint-javascript.yml'
      - 'frontend/**'
    branches-ignore:
      - 'renovate/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "yarn"
      
      - name: Install Dependencies
        run: |
          yarn set version latest
           yarn install --immutable
      
      # - name: Lint packages
      #   run: yarn lint
      
      - name: Format files (Prettier)
        run: yarn format

  # lint-go:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         version: latest
  #         only-new-issues: true
  #         args: --timeout=5m
