name: Unit Test JavaScript

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test-javascript.yml'
      - 'frontend/**'
      - 'package.json'
  pull_request:
    paths:
      - '.github/workflows/test-javascript.yml'
      - 'frontend/**'
      - 'package.json'
    branches-ignore:
      - 'renovate/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "yarn"

      - name: Install Dependencies
        run: |
          yarn set version latest
           yarn install --immutable

      # - name: Build Frontend Shared packages
      #   run: yarn shared:build

      - name: Run Frontend packages tests
        run: yarn test
